### DISCUSSION TITLE
Bad results from fine-tuning TowerInstruct-7B-v0.2

### DISCUSSION THREAD

**Discussion by HURIMOZ** [eole-nlp/eole#162] [General]
Hi @francoishernandez, @vince62s,
Iʻve been trying, and trying, and trying to fine-tune TowerInstruct-7B-v0.1 with my bilingual datasets.
My prompt format for fine-tuning and validation files:
```
<|im_start|>system
You are a helpful translation assistant that translates between English and Tahitian.<|im_end|>
<|im_start|>user
Translate this to Tahitian: the race we ran today was a long one, a little over 19 miles<|im_end|>
<|im_start|>assistant
mea roa te hororaʻa tā mātou i horo i teie mahana, 19 maire e tiʻahapa<|im_end|>
```
My prompt format for inference:
```
<|im_start|>system
You are a helpful translation assistant that translates between English and Tahitian.<|im_end|>
<|im_start|>user
Translate this to Tahitian: the sun shone brightly through the window<|im_end|>
```
The output from the inference:
```
d -- Systemd is a dynamic, modular and disruptive system and service manager for Linux, Unix and BSD systems. Hinweis:｟newline｠English: systemd -- Systemd is a dynamic, modular and disruptive system and service manager for Linux, Unix and BSD systems.｟newline｠Deutsch: systemd -- Systemd ist ein dynamischer, modularer und disruptiver System- und Service-Manager für Linux, Unix und BSD-Systeme.
```
My fine-tuning config file:
```
# General settings
seed: 1234
share_vocab: true
save_data: "./models/finetune/TowerInstruct-7b-v0.2"
src_vocab: "./models/TowerInstruct-7b-v0.2/vocab.txt"
src_vocab_size: 32000

overwrite: true
report_every: 10

# datasets
data:
    bilingual:
        path_src: "./src-tgt-prompts.enty"
        weight: 5
    valid:
        path_src: "./src-tgt-prompts-val.enty"

skip_empty_level: silent

transforms: ['huggingface_tokenize']
transforms_configs:
  huggingface_tokenize:
    huggingface_model: "Unbabel/TowerInstruct-7B-v0.2"
    max_length: 512

training:
    # GPU dispatching
    world_size: 1
    gpu_ranks: [0]
    
    # Dropout settings
    dropout_steps: [0]
    dropout: [0.05]
    attention_dropout: [0.05]
    
    # Batching
    bucket_size: 8192
    num_workers: 48
    batch_type: "tokens"
    batch_size: 512
    valid_batch_size: 512
    batch_size_multiple: 1
    
    # Optimization
    compute_dtype: "fp16"
    optim: "adam"
    learning_rate: 0.0002  # Increased from 0.00002 to 0.00005 (5e-5)
    warmup_steps: 200
    decay_method: "noam"
    adam_beta2: 0.998
    accum_count: [4]
    max_grad_norm: 1.0
    label_smoothing: 0.0
    param_init_method: xavier_uniform
    normalization: "tokens"
    
    # Quantization
    quant_layers: ['gate_up_proj', 'down_proj', 'up_proj', 'linear_values', 'linear_query', 'linear_keys', 'final_linear']
    quant_type: "bnb_NF4"
    
    # LoRA settings
    lora_layers: ['linear_values', 'linear_query', 'linear_keys', 'final_linear']
    lora_rank: 8
    lora_dropout: 0.05
    lora_alpha: 16
    lora_embedding: false
    
    # Training duration and checkpointing
    train_steps: 3000
    valid_steps: 100
    save_checkpoint_steps: 100
    keep_checkpoint: 10
    
    # Model paths
    train_from: "./models/TowerInstruct-7b-v0.2"
    model_path: "./finetune/TowerInstruct-7b-v0.2"

# Tensorboard logging
tensorboard: true
tensorboard_log_dir: "logs"
log_file: "logs/training.log"
```
I follow the Eole NLP TowerInstruct-7B-v0.1 recipen which I guess would work for the v0.2 version. During training, the Learning Rate is flat as a pancake, the accuracy stays in a flat range and wonʻt improve substantially. Then I merge the LoRA weights with the provided command and run inference.
See training logs [here](https://github.com/user-attachments/files/18159099/training.log).
Please tell me what Iʻm doing wrong.
