### ISSUE TITLE
CUDA Indexing Assertion Failure in Transformer Decoder

### ISSUE THREAD

**Issue by HURIMOZ** [eole-nlp/eole#145]
During the training of a Transformer-based neural machine translation bilingual model, a CUDA assertion failure is occurring in the indexing operation. See error [here](https://github.com/user-attachments/files/17826173/error.txt)

Here is my config file:
```
## IO
save_data: processed_data/
overwrite: True
seed: 1234
report_every: 100
valid_metrics: ["BLEU"]

### Vocab
src_vocab: processed_data/spm_src_8000_bpe.onmt_vocab
tgt_vocab: processed_data/spm_tgt_9000_bpe.onmt_vocab
share_vocab: false
#n_sample: -1

data:
    corpus_1:
        path_src: data/src-train.txt
        src_lang: fr
        path_tgt: data/tgt-train.txt
        tgt_lang: ty
    valid:
        path_src: data/FR-val.txt
        src_lang: fr
        path_tgt: data/TY-val.txt
        tgt_lang: ty
        #transforms: [onmt_tokenize]

transforms: [normalize, sentencepiece, filtertoolong]
transforms_configs:
  normalize:
    norm_quote_commas: true
    norm_numbers: true
  sentencepiece:
    #src_subword_type: sentencepiece
    src_subword_model: "processed_data/spm_src_8000_bpe.model"
    #tgt_subword_type: sentencepiece
    tgt_subword_model: "processed_data/spm_tgt_9000_bpe.model"
  #filtertoolong:
    #src_seq_length: 100
    #tgt_seq_length: 100


#dump_samples: true
#n_samples: 1000

# Number of candidates for SentencePiece sampling
#subword_nbest: 20
# Smoothing parameter for SentencePiece sampling
#subword_alpha: 0.1

training:
    # Run configuration
    model_path: models
    keep_checkpoint: 70
    save_checkpoint_steps: 1000
    train_steps: 70000
    valid_steps: 500
    #train_from: models/step_60000

    # Train on a single GPU
    world_size: 1
    gpu_ranks: [0]

    # batching
    batch_type: "tokens"
    batch_size: 1024
    valid_batch_size: 1024
    batch_size_multiple: 1
    accum_count: [10]
    accum_steps: [0]

    # Optimizer & Compute
    compute_dtype: "fp16"
    optim: "adam"
    #self_attn_backend: "pytorch"
    learning_rate: 1.5
    average_decay: 0.1
    #warmup_steps: 4000
    decay_method: "noam"
    adam_beta2: 0.998

    # Data loading
    bucket_size: 1024
    num_workers: 4
    prefetch_factor: 50

    # Hyperparams
    dropout_steps: [0]
    dropout: [0.1]
    attention_dropout: [0.1]
    max_grad_norm: 0
    label_smoothing: 0.1
    #param_init: 0
    param_init_method: "xavier_uniform"
    normalization: "tokens"

    #early_stopping: 3

tensorboard: true
tensorboard_log_dir: logs
log_file: logs/eole.log
   
# Pretrained embeddings configuration for the source language
embeddings_type: word2vec
#src_embeddings: data/en.wiki.bpe.vs25000.d300.w2v.txt
#pre_word_vecs_enc: data/en.wiki.bpe.vs25000.d300.w2v.txt
#tgt_embeddings:

model:
    architecture: "transformer"
    hidden_size: 512
    share_decoder_embeddings: false
    share_embeddings: true
    layers: 6
    heads: 8
    transformer_ff: 512
    embeddings:
        word_vec_size: 512
        position_encoding_type: "SinusoidalInterleaved"
        #position_encoding: true
```
The same config file used to work fine, until the system threw the error. I made a clean reinstall of CUDA 11.5, Nvidia Driver 555.42.06, CUDA Toolkit, etc. I deleted long sentences and now my longest line is 85 tokens for the source, and 73 tokens for the target. I even doubled my EBS storage but the issue is still breaking the training process.
