### ISSUE TITLE
filtertoolong working correctly?

### ISSUE THREAD

**Issue by Dagamies** [eole-nlp/eole#241]
I have a minor issue with FilterTooLong, it might be that I have not understood the way it works correctly. The issue is that I have following definition:

```yaml
transforms: [filtertoolong]
transforms_configs:
 filtertoolong:
   src_seq_length: 2056
   tgt_seq_length: 2056
```
I have double checked that longest sequence in my src and tgt for validation is 2055 tokens, data is pretokenized so no tokens should be added into each line. My validation src contains exactly 24 lines with 2055 tokens and no lines longer than that.
When doing evaluation I do get:
```bash
[2025-06-04 07:11:44,687 INFO] * Transform statistics for CorpusName.VALID(100.00%):
                        * FilterTooLongStats(filtered=24)
```
My question is if this is an error or feature? If feature, how many tokens is one supposed to add to filtertoolong spec to reach desired maximum sample length?
